# Analysis Configuration
# Grid and region settings for location evaluation

analysis:
  grid_size: 0.5              # miles between grid points
  max_radius: 25              # miles from center of region
  center_point: "City, State" # or lat/lon coordinates like [40.7128, -74.0060]