# API Configuration
# API keys and endpoints
apis:
  osrm:
    base_url: "https://router.project-osrm.org"
    timeout: 30
  # Deprecated Google Maps section
  google_maps:
    api_key: ""
    batch_size: 25
    rate_limit: 10
