# Destinations Configuration
# Regular destinations with flexible scheduling patterns

destinations:
  personal:
    - address: "3630 Harry Hines Blvd, Dallas, TX 75219"
      name: "Dallas Swing Dance Society"
      schedule:
        - days: "Sat"
          arrival_time: "21:00"
          departure_time: "23:30"
          
    - address: "3414 Elm St, Dallas, TX 75226"
      name: "Sons of Hermann Hall"
      schedule:
        - days: "Wed"
          arrival_time: "21:00"
          departure_time: "23:00"
          
# Schedule Pattern Definitions:
# Standard Patterns:
#   - Mon-Fri: Monday through Friday
#   - Mon,Wed,Fri: Specific weekdays
#   - Sat-Sun: Weekends
#
# Monthly Patterns:
#   - first_monday: First Monday of each month
#   - second_tuesday: Second Tuesday of each month
#   - third_saturday: Third Saturday of each month
#   - last_friday: Last Friday of each month
#   - last_sunday: Last Sunday of each month
#
# Frequency Calculations:
#   - Weekly patterns: 52 occurrences per year
#   - Monthly patterns: 12 occurrences per year
#   - Mixed patterns: Calculated based on actual calendar days