# Example configuration

# Analysis Weights Configuration
# Weights for composite scoring (must sum to 1.0)

weights:
  travel_time: 0.5    # Weight for travel time component
  travel_cost: 0.5    # Weight for transportation cost component